# External Secrets para Argo CD e Argo Workflows
# Integração com HashiCorp Vault via External Secrets Operator

---
# Credentials do Harbor para CI pipeline
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-credentials
  namespace: argo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: harbor-credentials
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: |
          {
            "auths": {
              "harbor.local": {
                "username": "{{ .username }}",
                "password": "{{ .password }}",
                "auth": "{{ printf "%s:%s" .username .password | b64enc }}"
              }
            }
          }
  data:
    - secretKey: username
      remoteRef:
        key: secret/data/cicd/harbor
        property: username
    - secretKey: password
      remoteRef:
        key: secret/data/cicd/harbor
        property: password

---
# Credentials do Argo CD para API access
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-credentials
  namespace: argo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argocd-credentials
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: secret/data/cicd/argocd
        property: admin-password

---
# GitHub token para acesso a repos privados
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: argo-events
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/cicd/github
        property: token

---
# Webhook secret do GitHub
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook-secret
  namespace: argo-events
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-webhook-secret
    creationPolicy: Owner
  data:
    - secretKey: secret
      remoteRef:
        key: secret/data/cicd/github
        property: webhook-secret

---
# Repository credentials para Argo CD (repos privados)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: github-repo-creds
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: https://github.com/your-org
        username: git
        password: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: secret/data/cicd/github
        property: token

---
# MinIO credentials para Argo Workflows artifacts
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argo-minio-credentials
  namespace: argo
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: argo-minio-credentials
    creationPolicy: Owner
  data:
    - secretKey: accesskey
      remoteRef:
        key: secret/data/minio/argo-user
        property: access-key
    - secretKey: secretkey
      remoteRef:
        key: secret/data/minio/argo-user
        property: secret-key

---
# Slack webhook para notificações (opcional)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: slack-webhook
  namespace: argocd
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: slack-webhook
    creationPolicy: Owner
  data:
    - secretKey: webhook-url
      remoteRef:
        key: secret/data/notifications/slack
        property: webhook-url
