# JWT Secrets for Supabase API Authentication
# ⚠️  IMPORTANTE: Gere secrets reais antes de aplicar!

# Para gerar secrets seguros:
# python3 -c "import secrets, base64; print(base64.urlsafe_b64encode(secrets.token_bytes(32)).decode().rstrip('='))"

apiVersion: v1
kind: Secret
metadata:
  name: supabase-jwt
  namespace: supabase
type: Opaque
stringData:
  # JWT Secret - base para geração dos tokens
  secret: "CHANGE-ME-base64-encoded-32-bytes-secret"
  
  # Anon Key - use no frontend (pública)
  # Esta key tem permissões limitadas, segura para expor no browser
  anonKey: "CHANGE-ME-base64-encoded-32-bytes-secret"
  
  # Service Role Key - use apenas no backend (privada)
  # Esta key bypassa Row Level Security, NUNCA exponha publicamente!
  serviceKey: "CHANGE-ME-base64-encoded-32-bytes-secret"
