---
# ClusterSecretStore usando Vault com Kubernetes Auth
# Permite que todos os namespaces consumam segredos do Vault
#
# Instalado automaticamente pelo módulo secrets.py
# Para criar manualmente: kubectl apply -f clustersecretstore-vault-kubernetes.yaml

apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "http://vault.vault.svc.cluster.local:8200"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "eso-role"
          serviceAccountRef:
            name: "external-secrets"
            namespace: "external-secrets"
