apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-config-vault
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-store
    kind: SecretStore
  target:
    name: app-config-vault
    creationPolicy: Owner
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: secret/data/prod/db
        property: password
