---
# ExternalSecret - Sincroniza segredos do Vault para K8s Secret
#
# Como usar:
# 1. Criar segredo no Vault:
#    kubectl -n vault exec vault-0 -- vault kv put secret/myapp username=admin password=secret123 api_key=abc123
#
# 2. Aplicar este ExternalSecret:
#    kubectl apply -f externalsecret-myapp.yaml
#
# 3. Verificar Secret sincronizado:
#    kubectl -n default get secret myapp-credentials -o yaml

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: myapp-external-secret
  namespace: default
spec:
  refreshInterval: 1h  # Sincroniza a cada 1 hora
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: myapp-credentials  # Nome do Secret K8s a ser criado
    creationPolicy: Owner    # ESO gerencia o ciclo de vida do Secret
    template:
      type: Opaque
      data:
        # Você pode fazer template dos dados
        config.yaml: |
          username: {{ .username }}
          password: {{ .password }}
          api_key: {{ .api_key }}
  
  data:
  # Mapeia cada campo do Vault para o Secret K8s
  - secretKey: username
    remoteRef:
      key: secret/myapp
      property: username
  
  - secretKey: password
    remoteRef:
      key: secret/myapp
      property: password
  
  - secretKey: api_key
    remoteRef:
      key: secret/myapp
      property: api_key

---
# Exemplo 2: Sincronizar todas as chaves de um secret do Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: database-credentials
  namespace: default
spec:
  refreshInterval: 30m
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: database-credentials
    creationPolicy: Owner
  
  dataFrom:
  # Sincroniza TODAS as chaves de secret/database
  - extract:
      key: secret/database

---
# Exemplo 3: Secret com múltiplos paths do Vault
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-all-secrets
  namespace: production
spec:
  refreshInterval: 15m
  
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  
  target:
    name: app-all-secrets
    creationPolicy: Owner
  
  data:
  # Database credentials
  - secretKey: db_host
    remoteRef:
      key: secret/production/database
      property: host
  
  - secretKey: db_password
    remoteRef:
      key: secret/production/database
      property: password
  
  # API keys
  - secretKey: stripe_api_key
    remoteRef:
      key: secret/production/api-keys
      property: stripe
  
  - secretKey: aws_access_key
    remoteRef:
      key: secret/production/api-keys
      property: aws_access_key
