apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: app-config
  namespace: apps
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-sm-store
    kind: SecretStore
  target:
    name: app-config
    creationPolicy: Owner
    type: Opaque
  data:
    - secretKey: API_KEY
      remoteRef:
        key: prod/app/api_key
