apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-sm-store
  namespace: apps
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: eso-aws
            namespace: apps
      role: arn:aws:iam::123456789012:role/eso-aws-sm
