# =============================================================================
# DigitalOcean DNS-01 ClusterIssuer
# =============================================================================
# Pré-requisitos:
# 1. Crie um Personal Access Token no DigitalOcean com permissão de escrita
#    https://cloud.digitalocean.com/account/api/tokens
# 2. Aplique o Secret primeiro, depois o ClusterIssuer
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: digitalocean-token
  namespace: cert-manager
type: Opaque
stringData:
  access-token: DIGITALOCEAN_TOKEN_AQUI
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-digitalocean
spec:
  acme:
    email: you@example.com
    # Produção: https://acme-v02.api.letsencrypt.org/directory
    # Staging:  https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-digitalocean-account-key
    solvers:
      - dns01:
          digitalocean:
            tokenSecretRef:
              name: digitalocean-token
              key: access-token
