# =============================================================================
# AWS Route53 DNS-01 ClusterIssuer
# =============================================================================
# Pré-requisitos:
# 1. Crie um IAM User com policy:
#    {
#      "Version": "2012-10-17",
#      "Statement": [
#        {
#          "Effect": "Allow",
#          "Action": "route53:GetChange",
#          "Resource": "arn:aws:route53:::change/*"
#        },
#        {
#          "Effect": "Allow",
#          "Action": [
#            "route53:ChangeResourceRecordSets",
#            "route53:ListResourceRecordSets"
#          ],
#          "Resource": "arn:aws:route53:::hostedzone/HOSTED_ZONE_ID"
#        },
#        {
#          "Effect": "Allow",
#          "Action": "route53:ListHostedZonesByName",
#          "Resource": "*"
#        }
#      ]
#    }
# 2. Aplique o Secret primeiro, depois o ClusterIssuer
# =============================================================================
apiVersion: v1
kind: Secret
metadata:
  name: route53-credentials
  namespace: cert-manager
type: Opaque
stringData:
  access-key-id: AWS_ACCESS_KEY_ID_AQUI
  secret-access-key: AWS_SECRET_ACCESS_KEY_AQUI
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-route53
spec:
  acme:
    email: you@example.com
    # Produção: https://acme-v02.api.letsencrypt.org/directory
    # Staging:  https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-route53-account-key
    solvers:
      - dns01:
          route53:
            region: us-east-1
            # hostedZoneID: Z1234567890ABC  # Opcional: especifique se tiver múltiplas zones
            accessKeyIDSecretRef:
              name: route53-credentials
              key: access-key-id
            secretAccessKeySecretRef:
              name: route53-credentials
              key: secret-access-key
