# HorizontalPodAutoscaler para Kong Gateway
# Auto-scaling baseado em CPU e memória

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: supabase-kong-hpa
  namespace: supabase
  labels:
    app: supabase-kong
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: supabase-kong
  
  minReplicas: 2
  maxReplicas: 6
  
  metrics:
  # CPU target
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  
  # Memory target
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300  # 5 minutos antes de scale down
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60  # 1 minuto antes de scale up
      policies:
      - type: Percent
        value: 100
        periodSeconds: 30
      - type: Pods
        value: 2
        periodSeconds: 30
      selectPolicy: Max
