# GitHub Actions Workflow - CI/CD para Supabase
# Deploy automático para cluster Kubernetes

name: Supabase CI/CD

on:
  push:
    branches:
      - main        # Produção
      - develop     # Teste
    paths:
      - 'manifests/**'
      - '.github/workflows/supabase-cicd.yml'
  pull_request:
    branches:
      - main
      - develop

env:
  KUBECTL_VERSION: '1.28.0'
  KUBECONFIG_SECRET: ${{ secrets.KUBECONFIG_PRODUCTION }}

jobs:
  # Job 1: Validação de manifests
  validate:
    name: Validate Manifests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Validate YAML syntax
        run: |
          find manifests -name '*.yaml' -o -name '*.yml' | while read file; do
            echo "Validating $file"
            kubectl apply --dry-run=client -f "$file" || exit 1
          done

      - name: Validate Kustomize
        if: hashFiles('manifests/kustomization.yaml') != ''
        run: |
          kubectl kustomize manifests --enable-helm

  # Job 2: Security scanning
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: 'manifests/'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy results to GitHub Security
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'

  # Job 3: Deploy para ambiente de TESTE
  deploy-test:
    name: Deploy to Test
    runs-on: ubuntu-latest
    needs: [validate, security]
    if: github.ref == 'refs/heads/develop'
    environment:
      name: test
      url: https://supabase-tst.yourdomain.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_TEST }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Deploy to test namespace
        run: |
          kubectl apply -f manifests/ -n supabase-tst
          kubectl rollout status deployment/supabase-kong -n supabase-tst --timeout=300s

      - name: Verify deployment
        run: |
          kubectl get pods -n supabase-tst
          kubectl get svc -n supabase-tst

      - name: Smoke test
        run: |
          KONG_IP=$(kubectl get svc supabase-kong -n supabase-tst -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          curl -f http://$KONG_IP:8000/auth/v1/health || exit 1
          echo "✓ Smoke test passed"

  # Job 4: Deploy para PRODUÇÃO
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [validate, security]
    if: github.ref == 'refs/heads/main'
    environment:
      name: production
      url: https://supabase.yourdomain.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_PRODUCTION }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Backup before deploy
        run: |
          # Trigger Velero backup antes do deploy
          kubectl create -f - <<EOF
          apiVersion: velero.io/v1
          kind: Backup
          metadata:
            name: supabase-pre-deploy-$(date +%Y%m%d-%H%M%S)
            namespace: velero
          spec:
            includedNamespaces:
              - supabase
            ttl: 168h
          EOF

          echo "Aguardando backup completar..."
          sleep 30

      - name: Deploy to production
        run: |
          kubectl apply -f manifests/ -n supabase
          
          # Aguarda rollout de todos os deployments
          kubectl rollout status deployment/supabase-kong -n supabase --timeout=600s
          kubectl rollout status deployment/supabase-postgrest -n supabase --timeout=600s
          kubectl rollout status deployment/supabase-gotrue -n supabase --timeout=600s
          kubectl rollout status deployment/supabase-realtime -n supabase --timeout=600s
          kubectl rollout status deployment/supabase-storage -n supabase --timeout=600s

      - name: Verify deployment
        run: |
          kubectl get pods -n supabase
          kubectl get svc -n supabase

      - name: Health check
        run: |
          # Aguarda 30s para services ficarem prontos
          sleep 30
          
          KONG_IP=$(kubectl get svc supabase-kong -n supabase -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
          
          echo "Testing Auth endpoint..."
          curl -f http://$KONG_IP:8000/auth/v1/health || exit 1
          
          echo "Testing REST endpoint..."
          curl -f http://$KONG_IP:8000/rest/v1/ || exit 1
          
          echo "Testing Realtime endpoint..."
          curl -f http://$KONG_IP:8000/realtime/v1/health || exit 1
          
          echo "✓ All health checks passed"

      - name: Notify success
        if: success()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "✅ Supabase deployed to production successfully!",
              attachments: [{
                color: 'good',
                text: `Commit: ${{ github.sha }}\nAuthor: ${{ github.actor }}\nURL: https://supabase.yourdomain.com`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

      - name: Notify failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "❌ Supabase deployment to production FAILED!",
              attachments: [{
                color: 'danger',
                text: `Commit: ${{ github.sha }}\nAuthor: ${{ github.actor }}\nCheck logs: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

  # Job 5: Rollback automático em caso de falha
  rollback:
    name: Rollback on Failure
    runs-on: ubuntu-latest
    needs: deploy-production
    if: failure() && github.ref == 'refs/heads/main'
    steps:
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: ${{ env.KUBECTL_VERSION }}

      - name: Configure kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG_PRODUCTION }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Rollback deployments
        run: |
          echo "Rolling back to previous version..."
          kubectl rollout undo deployment/supabase-kong -n supabase
          kubectl rollout undo deployment/supabase-postgrest -n supabase
          kubectl rollout undo deployment/supabase-gotrue -n supabase
          kubectl rollout undo deployment/supabase-realtime -n supabase
          kubectl rollout undo deployment/supabase-storage -n supabase
          
          echo "Waiting for rollback to complete..."
          kubectl rollout status deployment/supabase-kong -n supabase --timeout=300s

      - name: Notify rollback
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          custom_payload: |
            {
              text: "⚠️ Supabase rolled back due to deployment failure",
              attachments: [{
                color: 'warning',
                text: `Previous version restored. Check logs and fix issues before redeploying.`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
