apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: supabase
  labels:
    app: postgres
    backup: velero  # Label para Velero identificar para backup
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path  # Ajuste para sua StorageClass
  resources:
    requests:
      storage: 50Gi  # Ajuste conforme necessário
