apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: supabase
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432
    protocol: TCP
  selector:
    app: postgres
  # ClusterIP fixo opcional para estabilidade
  # clusterIP: 10.96.100.10
